/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as PickWorkspaceRouteImport } from './routes/pick-workspace'
import { Route as OrgSlugStaffRouteImport } from './routes/$orgSlug._staff'
import { Route as PublicCallbackRouteImport } from './routes/_public.callback'
import { Route as PublicCheckEmailRouteImport } from './routes/_public.check-email'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PortalOrgSlugRouteImport } from './routes/portal.$orgSlug'
import { Route as OrgSlugStaffIndexRouteImport } from './routes/$orgSlug._staff.index'
import { Route as PortalOrgSlugIndexRouteImport } from './routes/portal.$orgSlug.index'
import { Route as PortalOrgSlugRequestRouteImport } from './routes/portal.$orgSlug.request'
import { Route as OrgSlugStaffClientsIndexRouteImport } from './routes/$orgSlug._staff.clients.index'
import { Route as OrgSlugStaffClientsClientIdRouteImport } from './routes/$orgSlug._staff.clients.$clientId'
import { Route as OrgSlugStaffJobsIndexRouteImport } from './routes/$orgSlug._staff.jobs.index'
import { Route as OrgSlugStaffJobsNewRouteImport } from './routes/$orgSlug._staff.jobs.new'
import { Route as OrgSlugStaffSitesIndexRouteImport } from './routes/$orgSlug._staff.sites.index'
import { Route as PortalOrgSlugJobsJobIdRouteImport } from './routes/portal.$orgSlug.jobs.$jobId'
import { Route as OrgSlugStaffJobsJobIdIndexRouteImport } from './routes/$orgSlug._staff.jobs.$jobId.index'
import { Route as OrgSlugStaffJobsJobIdFieldRouteImport } from './routes/$orgSlug._staff.jobs.$jobId.field'
import { Route as OrgSlugStaffJobsJobIdQuoteRouteImport } from './routes/$orgSlug._staff.jobs.$jobId.quote'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const PickWorkspaceRoute = PickWorkspaceRouteImport.update({
  id: '/pick-workspace',
  path: '/pick-workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugStaffRoute = OrgSlugStaffRouteImport.update({
  id: '/_staff',
  getParentRoute: () => OrgSlugRoute,
} as any)
const PublicCallbackRoute = PublicCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckEmailRoute = PublicCheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PortalOrgSlugRoute = PortalOrgSlugRouteImport.update({
  id: '/portal/$orgSlug',
  path: '/portal/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugStaffIndexRoute = OrgSlugStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgSlugStaffRoute,
} as any)
const PortalOrgSlugIndexRoute = PortalOrgSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalOrgSlugRoute,
} as any)
const PortalOrgSlugRequestRoute = PortalOrgSlugRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => PortalOrgSlugRoute,
} as any)
const OrgSlugStaffClientsIndexRoute =
  OrgSlugStaffClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => OrgSlugStaffRoute,
  } as any)
const OrgSlugStaffClientsClientIdRoute =
  OrgSlugStaffClientsClientIdRouteImport.update({
    id: '/clients/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => OrgSlugStaffRoute,
  } as any)
const OrgSlugStaffJobsIndexRoute = OrgSlugStaffJobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => OrgSlugStaffRoute,
} as any)
const OrgSlugStaffJobsNewRoute = OrgSlugStaffJobsNewRouteImport.update({
  id: '/jobs/new',
  path: '/jobs/new',
  getParentRoute: () => OrgSlugStaffRoute,
} as any)
const OrgSlugStaffSitesIndexRoute = OrgSlugStaffSitesIndexRouteImport.update({
  id: '/sites/',
  path: '/sites/',
  getParentRoute: () => OrgSlugStaffRoute,
} as any)
const PortalOrgSlugJobsJobIdRoute = PortalOrgSlugJobsJobIdRouteImport.update({
  id: '/jobs/$jobId',
  path: '/jobs/$jobId',
  getParentRoute: () => PortalOrgSlugRoute,
} as any)
const OrgSlugStaffJobsJobIdIndexRoute =
  OrgSlugStaffJobsJobIdIndexRouteImport.update({
    id: '/jobs/$jobId/',
    path: '/jobs/$jobId/',
    getParentRoute: () => OrgSlugStaffRoute,
  } as any)
const OrgSlugStaffJobsJobIdFieldRoute =
  OrgSlugStaffJobsJobIdFieldRouteImport.update({
    id: '/jobs/$jobId/field',
    path: '/jobs/$jobId/field',
    getParentRoute: () => OrgSlugStaffRoute,
  } as any)
const OrgSlugStaffJobsJobIdQuoteRoute =
  OrgSlugStaffJobsJobIdQuoteRouteImport.update({
    id: '/jobs/$jobId/quote',
    path: '/jobs/$jobId/quote',
    getParentRoute: () => OrgSlugStaffRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pick-workspace': typeof PickWorkspaceRoute
  '/callback': typeof PublicCallbackRoute
  '/check-email': typeof PublicCheckEmailRoute
  '/login': typeof PublicLoginRoute
  '/portal/$orgSlug': typeof PortalOrgSlugRouteWithChildren
  '/portal/$orgSlug/request': typeof PortalOrgSlugRequestRoute
  '/$orgSlug/': typeof OrgSlugStaffIndexRoute
  '/portal/$orgSlug/': typeof PortalOrgSlugIndexRoute
  '/$orgSlug/clients/$clientId': typeof OrgSlugStaffClientsClientIdRoute
  '/$orgSlug/jobs/new': typeof OrgSlugStaffJobsNewRoute
  '/portal/$orgSlug/jobs/$jobId': typeof PortalOrgSlugJobsJobIdRoute
  '/$orgSlug/clients/': typeof OrgSlugStaffClientsIndexRoute
  '/$orgSlug/jobs/': typeof OrgSlugStaffJobsIndexRoute
  '/$orgSlug/sites/': typeof OrgSlugStaffSitesIndexRoute
  '/$orgSlug/jobs/$jobId/field': typeof OrgSlugStaffJobsJobIdFieldRoute
  '/$orgSlug/jobs/$jobId/quote': typeof OrgSlugStaffJobsJobIdQuoteRoute
  '/$orgSlug/jobs/$jobId/': typeof OrgSlugStaffJobsJobIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugStaffIndexRoute
  '/onboarding': typeof OnboardingRoute
  '/pick-workspace': typeof PickWorkspaceRoute
  '/callback': typeof PublicCallbackRoute
  '/check-email': typeof PublicCheckEmailRoute
  '/login': typeof PublicLoginRoute
  '/portal/$orgSlug/request': typeof PortalOrgSlugRequestRoute
  '/portal/$orgSlug': typeof PortalOrgSlugIndexRoute
  '/$orgSlug/clients/$clientId': typeof OrgSlugStaffClientsClientIdRoute
  '/$orgSlug/jobs/new': typeof OrgSlugStaffJobsNewRoute
  '/portal/$orgSlug/jobs/$jobId': typeof PortalOrgSlugJobsJobIdRoute
  '/$orgSlug/clients': typeof OrgSlugStaffClientsIndexRoute
  '/$orgSlug/jobs': typeof OrgSlugStaffJobsIndexRoute
  '/$orgSlug/sites': typeof OrgSlugStaffSitesIndexRoute
  '/$orgSlug/jobs/$jobId/field': typeof OrgSlugStaffJobsJobIdFieldRoute
  '/$orgSlug/jobs/$jobId/quote': typeof OrgSlugStaffJobsJobIdQuoteRoute
  '/$orgSlug/jobs/$jobId': typeof OrgSlugStaffJobsJobIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/pick-workspace': typeof PickWorkspaceRoute
  '/$orgSlug/_staff': typeof OrgSlugStaffRouteWithChildren
  '/_public/callback': typeof PublicCallbackRoute
  '/_public/check-email': typeof PublicCheckEmailRoute
  '/_public/login': typeof PublicLoginRoute
  '/portal/$orgSlug': typeof PortalOrgSlugRouteWithChildren
  '/portal/$orgSlug/request': typeof PortalOrgSlugRequestRoute
  '/$orgSlug/_staff/': typeof OrgSlugStaffIndexRoute
  '/portal/$orgSlug/': typeof PortalOrgSlugIndexRoute
  '/$orgSlug/_staff/clients/$clientId': typeof OrgSlugStaffClientsClientIdRoute
  '/$orgSlug/_staff/jobs/new': typeof OrgSlugStaffJobsNewRoute
  '/portal/$orgSlug/jobs/$jobId': typeof PortalOrgSlugJobsJobIdRoute
  '/$orgSlug/_staff/clients/': typeof OrgSlugStaffClientsIndexRoute
  '/$orgSlug/_staff/jobs/': typeof OrgSlugStaffJobsIndexRoute
  '/$orgSlug/_staff/sites/': typeof OrgSlugStaffSitesIndexRoute
  '/$orgSlug/_staff/jobs/$jobId/field': typeof OrgSlugStaffJobsJobIdFieldRoute
  '/$orgSlug/_staff/jobs/$jobId/quote': typeof OrgSlugStaffJobsJobIdQuoteRoute
  '/$orgSlug/_staff/jobs/$jobId/': typeof OrgSlugStaffJobsJobIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/onboarding'
    | '/pick-workspace'
    | '/callback'
    | '/check-email'
    | '/login'
    | '/portal/$orgSlug'
    | '/portal/$orgSlug/request'
    | '/$orgSlug/'
    | '/portal/$orgSlug/'
    | '/$orgSlug/clients/$clientId'
    | '/$orgSlug/jobs/new'
    | '/portal/$orgSlug/jobs/$jobId'
    | '/$orgSlug/clients/'
    | '/$orgSlug/jobs/'
    | '/$orgSlug/sites/'
    | '/$orgSlug/jobs/$jobId/field'
    | '/$orgSlug/jobs/$jobId/quote'
    | '/$orgSlug/jobs/$jobId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/onboarding'
    | '/pick-workspace'
    | '/callback'
    | '/check-email'
    | '/login'
    | '/portal/$orgSlug/request'
    | '/portal/$orgSlug'
    | '/$orgSlug/clients/$clientId'
    | '/$orgSlug/jobs/new'
    | '/portal/$orgSlug/jobs/$jobId'
    | '/$orgSlug/clients'
    | '/$orgSlug/jobs'
    | '/$orgSlug/sites'
    | '/$orgSlug/jobs/$jobId/field'
    | '/$orgSlug/jobs/$jobId/quote'
    | '/$orgSlug/jobs/$jobId'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/_public'
    | '/onboarding'
    | '/pick-workspace'
    | '/$orgSlug/_staff'
    | '/_public/callback'
    | '/_public/check-email'
    | '/_public/login'
    | '/portal/$orgSlug'
    | '/portal/$orgSlug/request'
    | '/$orgSlug/_staff/'
    | '/portal/$orgSlug/'
    | '/$orgSlug/_staff/clients/$clientId'
    | '/$orgSlug/_staff/jobs/new'
    | '/portal/$orgSlug/jobs/$jobId'
    | '/$orgSlug/_staff/clients/'
    | '/$orgSlug/_staff/jobs/'
    | '/$orgSlug/_staff/sites/'
    | '/$orgSlug/_staff/jobs/$jobId/field'
    | '/$orgSlug/_staff/jobs/$jobId/quote'
    | '/$orgSlug/_staff/jobs/$jobId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  PickWorkspaceRoute: typeof PickWorkspaceRoute
  PortalOrgSlugRoute: typeof PortalOrgSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pick-workspace': {
      id: '/pick-workspace'
      path: '/pick-workspace'
      fullPath: '/pick-workspace'
      preLoaderRoute: typeof PickWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/_staff': {
      id: '/$orgSlug/_staff'
      path: ''
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugStaffRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/_public/callback': {
      id: '/_public/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof PublicCallbackRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/check-email': {
      id: '/_public/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof PublicCheckEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/portal/$orgSlug': {
      id: '/portal/$orgSlug'
      path: '/portal/$orgSlug'
      fullPath: '/portal/$orgSlug'
      preLoaderRoute: typeof PortalOrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/_staff/': {
      id: '/$orgSlug/_staff/'
      path: '/'
      fullPath: '/$orgSlug/'
      preLoaderRoute: typeof OrgSlugStaffIndexRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/portal/$orgSlug/': {
      id: '/portal/$orgSlug/'
      path: '/'
      fullPath: '/portal/$orgSlug/'
      preLoaderRoute: typeof PortalOrgSlugIndexRouteImport
      parentRoute: typeof PortalOrgSlugRoute
    }
    '/portal/$orgSlug/request': {
      id: '/portal/$orgSlug/request'
      path: '/request'
      fullPath: '/portal/$orgSlug/request'
      preLoaderRoute: typeof PortalOrgSlugRequestRouteImport
      parentRoute: typeof PortalOrgSlugRoute
    }
    '/$orgSlug/_staff/clients/': {
      id: '/$orgSlug/_staff/clients/'
      path: '/clients'
      fullPath: '/$orgSlug/clients/'
      preLoaderRoute: typeof OrgSlugStaffClientsIndexRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/clients/$clientId': {
      id: '/$orgSlug/_staff/clients/$clientId'
      path: '/clients/$clientId'
      fullPath: '/$orgSlug/clients/$clientId'
      preLoaderRoute: typeof OrgSlugStaffClientsClientIdRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/jobs/': {
      id: '/$orgSlug/_staff/jobs/'
      path: '/jobs'
      fullPath: '/$orgSlug/jobs/'
      preLoaderRoute: typeof OrgSlugStaffJobsIndexRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/jobs/new': {
      id: '/$orgSlug/_staff/jobs/new'
      path: '/jobs/new'
      fullPath: '/$orgSlug/jobs/new'
      preLoaderRoute: typeof OrgSlugStaffJobsNewRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/sites/': {
      id: '/$orgSlug/_staff/sites/'
      path: '/sites'
      fullPath: '/$orgSlug/sites/'
      preLoaderRoute: typeof OrgSlugStaffSitesIndexRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/portal/$orgSlug/jobs/$jobId': {
      id: '/portal/$orgSlug/jobs/$jobId'
      path: '/jobs/$jobId'
      fullPath: '/portal/$orgSlug/jobs/$jobId'
      preLoaderRoute: typeof PortalOrgSlugJobsJobIdRouteImport
      parentRoute: typeof PortalOrgSlugRoute
    }
    '/$orgSlug/_staff/jobs/$jobId/': {
      id: '/$orgSlug/_staff/jobs/$jobId/'
      path: '/jobs/$jobId'
      fullPath: '/$orgSlug/jobs/$jobId/'
      preLoaderRoute: typeof OrgSlugStaffJobsJobIdIndexRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/jobs/$jobId/field': {
      id: '/$orgSlug/_staff/jobs/$jobId/field'
      path: '/jobs/$jobId/field'
      fullPath: '/$orgSlug/jobs/$jobId/field'
      preLoaderRoute: typeof OrgSlugStaffJobsJobIdFieldRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
    '/$orgSlug/_staff/jobs/$jobId/quote': {
      id: '/$orgSlug/_staff/jobs/$jobId/quote'
      path: '/jobs/$jobId/quote'
      fullPath: '/$orgSlug/jobs/$jobId/quote'
      preLoaderRoute: typeof OrgSlugStaffJobsJobIdQuoteRouteImport
      parentRoute: typeof OrgSlugStaffRoute
    }
  }
}

interface OrgSlugStaffRouteChildren {
  OrgSlugStaffIndexRoute: typeof OrgSlugStaffIndexRoute
  OrgSlugStaffClientsClientIdRoute: typeof OrgSlugStaffClientsClientIdRoute
  OrgSlugStaffJobsNewRoute: typeof OrgSlugStaffJobsNewRoute
  OrgSlugStaffClientsIndexRoute: typeof OrgSlugStaffClientsIndexRoute
  OrgSlugStaffJobsIndexRoute: typeof OrgSlugStaffJobsIndexRoute
  OrgSlugStaffSitesIndexRoute: typeof OrgSlugStaffSitesIndexRoute
  OrgSlugStaffJobsJobIdFieldRoute: typeof OrgSlugStaffJobsJobIdFieldRoute
  OrgSlugStaffJobsJobIdQuoteRoute: typeof OrgSlugStaffJobsJobIdQuoteRoute
  OrgSlugStaffJobsJobIdIndexRoute: typeof OrgSlugStaffJobsJobIdIndexRoute
}

const OrgSlugStaffRouteChildren: OrgSlugStaffRouteChildren = {
  OrgSlugStaffIndexRoute: OrgSlugStaffIndexRoute,
  OrgSlugStaffClientsClientIdRoute: OrgSlugStaffClientsClientIdRoute,
  OrgSlugStaffJobsNewRoute: OrgSlugStaffJobsNewRoute,
  OrgSlugStaffClientsIndexRoute: OrgSlugStaffClientsIndexRoute,
  OrgSlugStaffJobsIndexRoute: OrgSlugStaffJobsIndexRoute,
  OrgSlugStaffSitesIndexRoute: OrgSlugStaffSitesIndexRoute,
  OrgSlugStaffJobsJobIdFieldRoute: OrgSlugStaffJobsJobIdFieldRoute,
  OrgSlugStaffJobsJobIdQuoteRoute: OrgSlugStaffJobsJobIdQuoteRoute,
  OrgSlugStaffJobsJobIdIndexRoute: OrgSlugStaffJobsJobIdIndexRoute,
}

const OrgSlugStaffRouteWithChildren = OrgSlugStaffRoute._addFileChildren(
  OrgSlugStaffRouteChildren,
)

interface OrgSlugRouteChildren {
  OrgSlugStaffRoute: typeof OrgSlugStaffRouteWithChildren
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugStaffRoute: OrgSlugStaffRouteWithChildren,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface PublicRouteChildren {
  PublicCallbackRoute: typeof PublicCallbackRoute
  PublicCheckEmailRoute: typeof PublicCheckEmailRoute
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicCallbackRoute: PublicCallbackRoute,
  PublicCheckEmailRoute: PublicCheckEmailRoute,
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface PortalOrgSlugRouteChildren {
  PortalOrgSlugRequestRoute: typeof PortalOrgSlugRequestRoute
  PortalOrgSlugIndexRoute: typeof PortalOrgSlugIndexRoute
  PortalOrgSlugJobsJobIdRoute: typeof PortalOrgSlugJobsJobIdRoute
}

const PortalOrgSlugRouteChildren: PortalOrgSlugRouteChildren = {
  PortalOrgSlugRequestRoute: PortalOrgSlugRequestRoute,
  PortalOrgSlugIndexRoute: PortalOrgSlugIndexRoute,
  PortalOrgSlugJobsJobIdRoute: PortalOrgSlugJobsJobIdRoute,
}

const PortalOrgSlugRouteWithChildren = PortalOrgSlugRoute._addFileChildren(
  PortalOrgSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  PickWorkspaceRoute: PickWorkspaceRoute,
  PortalOrgSlugRoute: PortalOrgSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
